image: ruby:2.3

before_script:
  - apt-get update -yqqq
  - bundle install --jobs $(nproc)

minitest:
  script:
    - bundle exec rake test

rubocop:
  script:
    - bundle exec rake rubocop

variables:
  LANG: "en_US.UTF-8"
  LANGUAGE: "en_US.UTF-8"
  LC_ALL: "en_US.UTF-8"
