image: ruby:2.3

before_script:
  - echo "LC_ALL=\"en_US.UTF-8\"" >> /etc/default/locale
  - locale-gen en_US.UTF-8
  - update-locale LANG=en_US.UTF-8
  - bundle install --jobs $(nproc)

minitest:
  script:
    - bundle exec rake test

rubocop:
  script:
    - bundle exec rake rubocop
