before_script:
  - export LC_ALL=en_US.UTF-8
  - apt-get update -qq
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc) "${FLAGS[@]}"

minitest:
  script:
    - bundle exec rake test

rubocop:
  script:
    - bundle exec rake rubocop
