image: ruby:2.3

before_script:
  - export LANG=en_US.UTF-8
  - export LANGUAGE=en_US.UTF-8
  - export LC_ALL=en_US.UTF-8
  - bundler --version
  - bundle install --jobs $(nproc)

minitest:
  script:
    - bundle exec rake test

rubocop:
  script:
    - bundle exec rake rubocop
