image: ruby:2.3

before_script:
  - export LANG=en_US.UTF-8
  - export LC_ALL=en_US.UTF-8
  - bundle install

minitest:
  script:
    - bundle exec rake test

rubocop:
  script:
    - bundle exec rake rubocop
